version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        
  db:
    container_name: dbServer
    build: ./UmbracoData
    restart: always
    environment:
      SA_PASSWORD: "ComplexPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1400:1433"
    volumes:
      - database:/var/opt/mssql
  
  umbraco:
    container_name: web
    build: ./Umbraco
    volumes:
      - media:/app/wwwroot/media
      - logs:/app/umbraco/Logs
      - ./Umbraco/appsettings.json:/app/appsettings.json
      - ./Umbraco/Views:/app/Views
    ports:
      - "8000:80"
    depends_on:
      - db

volumes:
  database:
  media:
  logs: