version: "3"

services:
  db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      SA_PASSWORD: "ComplexPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1400:1433"
    volumes:
      - database:/var/opt/mssql
    
  umbraco:
    build: ./Umbraco
    ports:
      - "8000:80"
    depends_on:
      - db

volumes:
  database: